apiVersion: v1
kind: Service
metadata:
  name: code-server
  labels:
    app: code-server
  annotations:
    dev.okteto.com/auto-ingress: "private"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: code-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: code-server
      containers:
      - image: codercom/code-server:latest
        imagePullPolicy: Always
        name: code-server
        args: ["--allow-http"]
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: "password"
        volumeMounts:
        - name: storage # must match the volume name, above
          mountPath: "/home/coder/project"
---
